### ISSUE TITLE
When manually realigning the subs inside of mpv it still pauses at the original time.

### ISSUE THREAD

**Issue by xrishox** [Ben-Kerman/mpv-sub-pause#1]
When I need to offset the subs inside of mpv to fix mistimed subs, it seems to autopause at the original time rather than the re-aligned time. Is there any way to fix this?

**Comment by Renji-XD** [comment]
There is a sub-delay property in mpv. Not quite sure if its related to that but if you like you can try out the attached version which simply adds the value on top (just extract and replace the lua file in the scripts folder) and see if that helps.

[sub-pause.zip](https://github.com/Ben-Kerman/mpv-sub-pause/files/5478839/sub-pause.zip)

**Comment by xrishox** [comment]
this seemed to fix my issue. perhaps this should get merged in. there are a lot of people who get subs that aren't perfectly aligned which can cause problems. thanks a lot.

**Comment by Ben-Kerman** [comment]
Fixed by 1c6ae10f
